### PR TITLE
Added html support and a html.yml for people on chromebooks

### PR DESCRIPTION
**Pull request by LEVIXDDLMAO**
Tbh this wont be seen

### CODE REVIEW

**Comment by MemeHoovy** [comment]
> Tbh this wont be seen

bet

**Comment by MemeHoovy** [comment]
> > Tbh this wont be seen
> 
> bet

I'm sure rozebud will see this.

**Review by MemeHoovy — APPROVED** [review]

**Comment by LEVIXDDLMAO** [comment]
dope, I finally got this to port after 3 weeks

**Comment by LEVIXDDLMAO** [comment]
now im working on os engine :D

**Review by SanicBTW — APPROVED** [review]
Looks cool

**Comment by LEVIXDDLMAO** [comment]
Thx :D

**Comment by MemeHoovy** [comment]
> Looks cool

agreed

**Comment by LEVIXDDLMAO** [comment]
:D you guys are the best

**Comment by LEVIXDDLMAO** [comment]
D: Im sad

**Comment by MemeHoovy** [comment]
> D: Im sad

why?

**Comment by LEVIXDDLMAO** [comment]
because i couldn't port wesnday infidlitry part 2 ( i spelled it wrong ik )

**Comment by MemeHoovy** [comment]
> because i couldn't port wesnday infidlitry part 2 ( i spelled it wrong ik )

yeah, lunar hates ports

**Comment by MemeHoovy** [comment]
> lol it said only for desktop

he made it so you can only compile to desktop

**Comment by LEVIXDDLMAO** [comment]
fuck ill have to find out how to fix it

**Comment by MemeHoovy** [comment]
> fuck ill have to find out how to fix it

delete this in project.xml
```
<error value="Targets besides desktop are not supported" unless="desktop" />
```

**Comment by LEVIXDDLMAO** [comment]
okay, ill do it after i test my mod thing im working on

**Comment by MemeHoovy** [comment]
> okay, ill do it after i test my mod thing im working on

alright

**Comment by LEVIXDDLMAO** [comment]
:D Im trying to make acc and unloaded and edd work on it and then add more like the steve mod hardcore

**Comment by MemeHoovy** [comment]
> :D Im trying to make acc and unloaded and edd work on it and then add more like the steve mod hardcore

cool

**Comment by LEVIXDDLMAO** [comment]
Yeah, its being dumb, It didnt show them

**Comment by MemeHoovy** [comment]
> Yeah, its being dumb, It didnt show them

oh

**Comment by LEVIXDDLMAO** [comment]
Yeah i think its because there was too much songs

**Comment by LEVIXDDLMAO** [comment]
image
 how the funk

**Comment by MemeHoovy** [comment]
> image how the funk

remove sys in discord.hx, and the sleep thing

**Comment by SanicBTW** [comment]
Now port a mod to fps plus

**Comment by LEVIXDDLMAO** [comment]
ah okay

**Comment by LEVIXDDLMAO** [comment]
> Now port a mod to fps plus
> 
> Lmaoo

i feel like thats gonna be hard, but give me a link ill do it

**Comment by SanicBTW** [comment]
> > Now port a mod to fps plus
> > 
> > Lmaoo
> 
> i feel like thats gonna be hard, but give me a link ill do it

Alright wait a min

**Comment by LEVIXDDLMAO** [comment]
kk

**Comment by SanicBTW** [comment]
bro imagine what would rozebud think when he sees this thread 🥶

**Comment by LEVIXDDLMAO** [comment]
image
yoo

**Comment by SanicBTW** [comment]
hayo levi i recommend fixing the framerate on html5 targets, go to main.hx on add child and replace that with this: `		addChild(new FlxGame(0, 0, Startup, 1, #if html5 60 #else 144 #end, #if html5 60 #else 144 #end, true));
`

**Comment by LEVIXDDLMAO** [comment]
ah okay! i have to fix the songs

**Comment by LEVIXDDLMAO** [comment]
cna you give me the line?

**Comment by SanicBTW** [comment]
line 25 on Main.hx

**Comment by LEVIXDDLMAO** [comment]
kk

**Comment by LEVIXDDLMAO** [comment]
there

**Comment by SanicBTW** [comment]
💔

**Pull request closed without merging**
